### ISSUE TITLE
Href toevoegen bij link

### ISSUE THREAD

**Issue by Jesse-Kramer** [Jason2426/fix-the-flow-interactive-website#4]
Rond regel 34 staat in de paragraph een link, vergeet deze geen href te geven.

**Comment by Jason2426** [comment]
https://github.com/Jason2426/fix-the-flow-interactive-website/blob/11d5356d457bcdd72b3da6a4206f62c9a0054727/index.html#L34

Gefixt door een ahref element toe te voegen thx nogmaals top gozertje!! 👍
