### ISSUE TITLE
H1 kop toevoegen

### ISSUE THREAD

**Issue by Jesse-Kramer** [Jason2426/fix-the-flow-interactive-website#5]
Voeg minimaal en maximaal 1 h1 kop toe aan elke pagina.

**Comment by Jason2426** [comment]
https://github.com/Jason2426/fix-the-flow-interactive-website/blob/a639d314a546b4bcbe416f50d4661f2516ae8ba7/index.html#L15

Gelijk gefixt dankjewel toffe gozer gast !! 😁 😜 💀
